apiVersion: v1
kind: Service
metadata:
  name: ops-agent-svc
  labels:
    app: ops-agent
spec:
  type: NodePort
  selector:
    app: ops-agent
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30080
